name: Run Checks

on: [push, pull_request]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10-dev]

    name: Run checks
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run checks (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip nox
          nox

      - name: Run checks (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip nox
          nox

      - name: Run checks (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m venv .venv
          . .venv\Scripts\activate.bat
          python -m pip install -U pip nox
          nox
